name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Upload build artifacts       
      uses: actions/upload-artifact@v2      
      with:        
          name: insecure-bank.war        
          path: target/insecure-bank.war
    - name: Install Vantage
      run: wget https://github.com/whitehatsec/vantage-prevent-distributions/releases/latest/download/VantagePrevent-Ubuntu-22_04.deb
    - name: Vantage location
      run: ls
      
    - name: Install Vantage
    - run: sudo apt-get install -y -f [./VantagePrevent-Ubuntu-22_04.deb | /home/runner/work/insecure-bank/insecure-bank]
    
    - name: Vantage installed location
    - run: ls
      
